// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrA8bAi7cn6aDnahAB20l1VzudQbFdHXQ',
    appId: '1:862377076819:web:c6311e8114b7da2fdcfea6',
    messagingSenderId: '862377076819',
    projectId: 'free-kash',
    authDomain: 'free-kash.firebaseapp.com',
    storageBucket: 'free-kash.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YY3LtskkZ5bCeX9dPV50Q0I4y-hgFb4',
    appId: '1:862377076819:android:99c7f86a3a6db1a0dcfea6',
    messagingSenderId: '862377076819',
    projectId: 'free-kash',
    storageBucket: 'free-kash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBFckw0KOaFq7ojO3P5UveDggsp53gJrs',
    appId: '1:862377076819:ios:4f21c90a31f5c633dcfea6',
    messagingSenderId: '862377076819',
    projectId: 'free-kash',
    storageBucket: 'free-kash.appspot.com',
    iosBundleId: 'com.example.freeKash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBFckw0KOaFq7ojO3P5UveDggsp53gJrs',
    appId: '1:862377076819:ios:dc2550c8e02154dadcfea6',
    messagingSenderId: '862377076819',
    projectId: 'free-kash',
    storageBucket: 'free-kash.appspot.com',
    iosBundleId: 'com.example.freeKash.RunnerTests',
  );
}
